source/scripting-basics.md

The in text link was linking to the .md file instead .html resulting in a 404

Fixed link to game-loop

---

api/source/StructureController.md

Adding the info about passable hostile creeps from this PTR changelog http://support.screeps.com/hc/en-us/community/posts/208260949-PTR-Changelog-2016-09-23

Hostile creeps are passable in safe mode

---

source/creeps.md

Edit:
-A standard spawn (structure) can only spawn ,  this provides new users to have a clear clarification of "standard spawn"
-Small typo's and readability of certain sentences.

Readability and small typo's

---

api/source/Creep.md
api/source/Game.md
api/source/Map.md
api/source/Market.md
api/source/RawMemory.md
api/source/Room.md
api/source/RoomPosition.md
api/source/RoomVisual.md
api/source/StructureContainer.md
api/source/StructureLink.md
api/source/StructureSpawn.md
api/source/StructureStorage.md
api/source/StructureTerminal.md

`var` should no longer be used in code. Instead enforce the use of `let` and `const`.

Replace var with let/const

---

source/contributed/modifying-prototypes.md

Change link to screeps profile

Change name and link

---

source/contributed/caching-overview.md

Hope this is alright @tedivm. Just noticed this small syntax difference when viewing the article.

Fix hyperlink in caching-overview.md

---

api/source/StructureNuker.md

Made clear that withdrawing resources from the Nuker is impossible.

Updated StructureNuker readme.

---

api/source/StructureSpawn.md

This is related to https://github.com/screeps/engine/pull/38 .

Spawn.spawnCreep documentation

---

source/control.md

Added capital letters to Controller in some places to keep consistency and fixed some wording mistakes.

Fix wording in control.md

---

source/third-party.md

Third-party list extended with screeps-server-mockup

---

source/minerals.md

Minor typo and missing article

StructureLab contains the boostCreep method

---

source/third-party.md

Added the Screeps Monitor Android app to the Third Party Tools list.

Added Screeps Monitor to the Third Party Tools list

---

source/third-party.md

add Kotlin to Language Support
Please let me know if you need anything else.

add Kotlin to 3rd Party

---

source/third-party.md

This starter and surrounding libraries are definitely "alpha level", but if more people use it then it could definitely become more mature.

Add Rust starter to Third Part Tools

---

api/source/Creep.md
api/source/PathFinder.md
api/source/Tombstone.md
api/source/constants.md
source/introduction.md
source/invaders.md
source/minerals.md
source/third-party.md

- Creeps can withdraw from tombstones.
- Creeps cannot withdraw from other creeps. The transfer() method should be used instead.

Clarify Creep.withdraw() parameters.

---

api/source/RoomPosition.md

position.createConstructionSite example call was incorrect.

Fixing position.createConstructionSite name arg

---

api/source/Map.md
api/source/Room.Terrain.md
api/themes/screeps-api/layout/index.jade

Description and usage examples of [PR-83](https://github.com/screeps/engine/pull/83). Interfaces confirmation required.

feat: Room.Terrain docs

---

api/source/Room.md

Add missing Room.find constant, fix #165

---

source/control.md

Factory available at RCL 7, Nuker at RCL 8

Add Factory and Nuker to RCL levels

---

api/source/Room.md

Fixes getEventLog
